// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Todo struct {
	ID          int64
	Description string
	Done        bool
	CreatedAt   time.Time
}
