// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package database

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (description, user_id, done)
VALUES (?, ?, false)
`

type CreateTodoParams struct {
	Description string
	UserID      int64
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo, arg.Description, arg.UserID)
	return err
}

const listTodos = `-- name: ListTodos :many
SELECT id, description, done, created_at
FROM todos
WHERE done = false
AND user_id = ?
ORDER BY id
`

type ListTodosRow struct {
	ID          int64
	Description string
	Done        bool
	CreatedAt   time.Time
}

func (q *Queries) ListTodos(ctx context.Context, userID int64) ([]ListTodosRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodosRow
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
